//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace codecabc.Unity.Analyzers.Resources {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("codecabc.Unity.Analyzers.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Correctness.
        /// </summary>
        internal static string CategoryCorrectness {
            get {
                return ResourceManager.GetString("CategoryCorrectness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Performance.
        /// </summary>
        internal static string CategoryPerformance {
            get {
                return ResourceManager.GetString("CategoryPerformance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Type Safety.
        /// </summary>
        internal static string CategoryTypeSafety {
            get {
                return ResourceManager.GetString("CategoryTypeSafety", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Gameobject or component should declare their parenting relation or use a NoHierarchyValidation attribute. Use Enumerable versions for lists and arrays..
        /// </summary>
        internal static string NoHierarchyAttribute {
            get {
                return ResourceManager.GetString("NoHierarchyAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Add NotNull attribute..
        /// </summary>
        internal static string NoNotNullAttributeCodeFixTitle {
            get {
                return ResourceManager.GetString("NoNotNullAttributeCodeFixTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à SerializedField should have a NotNull or a CanBeNull attribute..
        /// </summary>
        internal static string NoNotNullAttributeErrorDescription {
            get {
                return ResourceManager.GetString("NoNotNullAttributeErrorDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Add NonSerialized attribute..
        /// </summary>
        internal static string NonSerializedAttributeForUnityObjectsCodeFixTitle {
            get {
                return ResourceManager.GetString("NonSerializedAttributeForUnityObjectsCodeFixTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Unity objects that are not serialized should have a NonSerialized attribute..
        /// </summary>
        internal static string NonSerializedAttributeForUnityObjectsErrorDescription {
            get {
                return ResourceManager.GetString("NonSerializedAttributeForUnityObjectsErrorDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à SerializedField should have a EnumerableNotNull or a EnumerableCanBeNull attribute..
        /// </summary>
        internal static string NoNullabilityForEnumerableAttribute {
            get {
                return ResourceManager.GetString("NoNullabilityForEnumerableAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Add EnumerableNotNull attribute..
        /// </summary>
        internal static string NoNullabilityForEnumerableCodeFixTitle {
            get {
                return ResourceManager.GetString("NoNullabilityForEnumerableCodeFixTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Numeric fields are better to be constrained. If whole range is valid use a NumericAnyValue. Otherwise use at least one of MinValue or MaxValue. Use Enumerable versions for lists and arrays..
        /// </summary>
        internal static string NoNumericAttributeErrorDescription {
            get {
                return ResourceManager.GetString("NoNumericAttributeErrorDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Unity&apos;s Gameobjects or components should have either a RequireComponents or a NoComponentRequired. Use Enumerable versions for lists and arrays..
        /// </summary>
        internal static string NoRequireComponentsAttribute {
            get {
                return ResourceManager.GetString("NoRequireComponentsAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à String fields are better when constrained. If any value is acceptable use StringValueAny. Otherwise use one of : StringMatchRegex, StringNotEmpty, StringNotWhiteSpace, , PathValidation, AddressableValidation, ResourceValidation. Use Enumerable versions for lists and arrays..
        /// </summary>
        internal static string NoStringAttributeErrorDescription {
            get {
                return ResourceManager.GetString("NoStringAttributeErrorDescription", resourceCulture);
            }
        }
    }
}
